FROM php:8.2-fpm
RUN apt-get update && apt-get install -y libicu-dev libzip-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev pkg-config && docker-php-ext-configure gd --with-jpeg --with-freetype && docker-php-ext-install -j$(nproc) intl zip gd mbstring mysqli pdo_mysql opcache && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
COPY backend/ /var/www/html/backend/
EXPOSE 9000
CMD ["php-fpm"]
