FROM php:8.2-apache
RUN apt-get update && apt-get install -y libicu-dev libzip-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev pkg-config && docker-php-ext-configure gd --with-jpeg --with-freetype && docker-php-ext-install -j$(nproc) intl zip gd mbstring mysqli pdo_mysql opcache && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN a2enmod rewrite
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf /etc/apache2/apache2.conf
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
