server {
  listen 80;
  server_name __APP_SERVER_NAME__;

  root /srv/static/__APP_NAME__;
  index index.html index.htm;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ^~ /cgi-bin/ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/html/backend/WEB-INF/cgi$fastcgi_script_name;
    fastcgi_index index.php;
    fastcgi_pass __APP_NAME___backend:9000;
    fastcgi_buffering off;
  }

  location ~* \.(?:css|js|jpg|jpeg|png|gif|ico|svg|webp)$ {
    expires 7d;
    access_log off;
    add_header Cache-Control "public";
  }

  location ~ /\. {
    deny all;
  }
}
